### PR TITLE
Delete extra sign up panel

### PR DESCRIPTION
**Pull request by prince-chrismc**
it's already in the footer

What's live right now

image

### CODE REVIEW

**Comment by prince-chrismc** [comment]
@RubenRBS When you tested these locally, how did you do it? The scripts dont code the remote protocol and just work 😕 

Did you make a webserver to have https?

image

**Comment by memsharded** [comment]
This is not why I see in the live web? I am a bit confused.

**Comment by prince-chrismc** [comment]
It's only on the terms and conditionshttps://conan.io/terms-conditions.html

**Comment by RubenRBS** [comment]
@prince-chrismc I asked @davidsanfal to deploy the site to a staging domain, and tested from there

**Review by RubenRBS — APPROVED** [review]

**Pull request merged**
