### PR TITLE
Shuffle Our Users

### LINKED ISSUE #133: Make space for more logos
We are going to add more company logos. It is necessary to have a place to add them easily.

Alternatives:

- Have some animation that changes them, randomly, fade-in-out, or something like that.
- Make the grid bigger, to include more of them
- Other kind of animation?

cc /@nadavc-jfrog

### PR DESCRIPTION
**Pull request by uilianries**
closes #133

~I've updated "Our Users" table to 10 slots only, because we have only 15 companies listed~

UPDATE:

I made a small screen record illustrating the animation: 

website

### CODE REVIEW

**Comment by uilianries** [comment]
> This PR has tons of changes that might be unrelated? Removed files?. If there is some refactor or improvement prior to the task, then better a dedicated PR.

That's the of gulp, the built files. I can remove all that keep only what I changed, but the index.html won't reflect the src/. IMO pushing all those file is wrong, we should use a separated branch where the CI push those files after a build.

> Keep the current matrix. It doesn't matter the one that is removed enters back again in one step (did you try it and didn't work?)

I works indeed, I just wanted to avoid only one icon changing, but if we have more logos, I'll keep 15 positions

> Probably the animation should be a bit faster?

Totally possible

I gonna revert my initial change (removing the built files)

**Comment by memsharded** [comment]
> That's the of gulp, the built files. I can remove all that keep only what I changed, but the index.html won't reflect the src/. IMO pushing all those file is wrong, we should use a separated branch where the CI push those files after a build.

Yes, I agree the current process is not right, the built files shouldn't be committed, but managed by CI, but right now we don't control that process, so it is a bit inconvenient.

Who could managed this @ankushchadha?

**Comment by uilianries** [comment]
Done, only source are in this PR.

**Comment by uilianries** [comment]
BTW IF the new website consumes the master branch directly, it won't work, because we don't have the built files here.

My suggestion is merging into staging branch and the CI (travis), build and push into master.

**Comment by memsharded** [comment]
Please rebase from develop, that after https://github.com/conan-io/website/pull/138 removed production generated files in teh develop branch.

**Pull request merged**
